# sae2022-bank-2a3
sae2022-bank-2a3 created by GitHub Classroom

Vous devez ici présenter l'équipe et décrire un peu le projet puis mettre les liens à vos documents.
== Livrables

[cols="1,2,2,5",options=header]
|===
| Date    | Nom         |  Lien                             | Retour
| 03/04   | Gantt V1    |                                                              | pas de retour envoyé moi par mail le pdf
|         | CdC V1      |                                   |   https://github.com/IUT-Blagnac/sae2022-bank-2a3/blob/main/RetourCDCv1.adoc
|         | Suivi Projet |                                   |   Votre projet étant privé je ne peux pas consulter les commits...
Vous devez : créer une arborescence du projet ex images, sources, document ..  à faire
Vous devez respecter les formats de documents demandés : gantt en pdf (je ne peux pas lire votre gantt) et documents en ASCIIdoc.
Vous n'aviez pas créé le readme... Je l'ai fait
Les issues du projets doivent correspondre à votre gantt ici pas possible j'en ai qu'une... ils doivent être affectés, hiérarchisés, ordonnés en cours archevés...

| 22/04  | CdC V2/V3 final|      manque lien !!                               |  1,5/2	Manque nom du client. Manque liens dans le sommaire.
1	/2 Manque lien dans le readme ! Relisez-vous il y a des fautes.
1/4	Très succinct : contexte économique, problématique … De plus l'appli ne concerne pas que les guichetiers !
1,5/4	Il faut expliquer le rôle des utilisateurs ! Donner le UC V0 de l'appli , les aspects techniques !
1,5/4	Je n'ai que le UC de V1 !! Non commenté.
3/4	Il manque les contraintes juridiques et les règles de gestion.
	
9,5	

|         | Gantt V2    |                               |     
|         | Gantt V3 |         |     
|         | Doc. Tec. V1 |        |    
|         | Doc User V1    |        |retard V1
|         | Recette V1  |                      | 
|         | Suivi projet|   | 
| 22/05   | Gantt V2  à jour    |       | 
|         | Doc. Util. V1 |         |         
|         | Doc. Tec. V1 |                |     
|         | Code V1     |                     | 
|         | Recette V1 |                      | 
|         | Gantt V3 à jour   |                      | 
|         | `jar` projet |    | 
| 05/06   | Gantt V3 à Jour  |    |  
|         | Doc. Util. V2 |         |  https://github.com/IUT-Blagnac/sae2022-bank-2a3/blob/main/documentation_utilisateur_v2.adoc         
|         | Doc. Tec. V2 |    |  https://github.com/IUT-Blagnac/sae2022-bank-2a3/blob/main/documentation_technique_v2.adoc   
|         | Code V2     |                       |
|         | Recette V2  |   |
|         | `jar` projet |     |
|12/06   | Gantt V3 à Jour  |    |  
|         | Doc. Util. V3 |         |           
|         | Doc. Tec. V3 |    |     
|         | Code V3     |                       |
|         | Recette V3  |   |
|         | `jar` projet |     |
|===
== Les critères d'évaluation :SAE S2.05 Gestion de projet

=== CDCU
• Page de garde (Version, date, équipe, projet ...), Sommaire
• Présentation du sujet
◦ contexte, objectifs, à quel problème répond-t-il ?
• Analyse de l’existant
• Analyse des besoins incluant V2 et V3
• Analyse des contraintes
◦ techniques & organisationnelles


=== Gestion de projet
Gantts complets, cohérents avec les issues et à jour (tâches, resp., avancements...)
Format (Gantt en pdf, docs en asciidoc) et arborescence du dépôt
Sources versionnées, commit réguliers et commentés...
Gestion du projet sous Github (issues, millestones, avancée ...), prise en compte des remarques dans le readme

== Rappel des consignes


Définir et ordonnancer les tâches du projet, les formaliser via des issues, les classer (Must/Should/Could/Will), les affecter,

Faire un GANTT à l’aide de l’outil de votre choix et le déposer en pdf de préférence sur 1 seule page,

créer les issues du projet.
