Revoir le document cahier de chages et budjet du cours.
= Retours CDC

== Page de garde (Version, date, équipe, projet ...)
elle ne comporte que vos noms à compléter

 
== Sommaire  
Les titres du sommaires ne sont pas conformes au titres qui suivents ???

=== Objectif du projet
Détailler un peu plus


Qui est le client ? Qui sont les utilisateurs de l'application ?

Pour moi deux les guichetiers et les chefs d'agences.
Il faut aussi produire un texte indiquant que les guichetiers pourront créer de nouceaux clients et faire les opétations courante...
Que les chefs d'agences pourront gérer les employé et les opérations exeptionnelles...

L'application commence par une analyse de l'exsitant puis sera découpée en plusieurs versions à la demande du client

== analyse de l'existant

 
Description du système d’information actuel de l’organisation :
Les processus informatisés ou non, impactés par le projet seront décrits
(à l’aide d’un outil de modélisation).
 ... voir docu gestion de projet
 
 Vous devriez ici avoir les UC de l'existant et vous devriez les commenter...
 
 
== les contraintes liées au projet


Vous devriez indiquer qu'il y aura un lien avec une base de donnée existante, que l'appli initiale sera fournie en java avec une IHM cpdée en java FX
Que vous devez travailler avec une équipe constituée de ...
Que les échances des différentes version du projet sont ...
...


==== analyse des nouveaux besoins
Votre lien vers usecase ne fonctionne pas. Quand on met une image il faut un titre et vous devez la commenter...
Indiquer les fonctionnalités qu'on vous a demandé pour la V1


Il faut ici que vous reformulier la demande du client afin de vous assurer que vous avez bien compris.

== La description de la solution

Un use case commenté peut être une bonne idée.

Une maquette des interfaces...

== Modalités d’organisation pour la suite du projet

qui fait quoi ici le gant commenté c'est bien

Quels sont les dates de livraison de chaque livrable,

Quelles seront les modalités de la livraison recette, doc...



== Enveloppe  
Vous avez un doc de Mme pendaries depuis votre gantt vous avec les heures prévisionnelles de codage de test, de rédaction...
